ecopedia/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path
from commons import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('animales', views.animals, name='animals'),
    path('quiz/', views.quiz, name='quiz'),
    path('quiz/<quiz_id>', views.quiz, name='quiz'),
    path('failure', views.failure, name='failure'),
    path('certificate/', views.certificate, name='certificate'),
    path('certificate/<validation_id>', views.certificate, name='certificate'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

commons/models.py
from django.db import models

# Create your models here.
class Animal(models.Model):
    name = models.CharField(max_length=256)
    slug = models.CharField(max_length=256)
    description = models.TextField()
    image_link = models.CharField(max_length=1024)
    map_link = models.CharField(max_length=1024)

class Tip(models.Model):
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    description = models.TextField()

class Question(models.Model):
    description = models.TextField()

class Quiz(models.Model):
    quid = models.CharField(max_length=6)
    expires_at = models.DateTimeField()
    questions = models.ManyToManyField(Question)
    active = models.BooleanField(default=True)

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    description = models.TextField()
    is_correct = models.BooleanField(default=False)

commons/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from datetime import datetime, timedelta, timezone
from commons.models import *
from io import BytesIO

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.units import inch

import random
import string
# Create your views here.
def home(request):
    animals = Animal.objects.all()
    return render(request,'index.html',locals())

def animals(request):
    animals = Animal.objects.all()
    return render(request,'animales.html',locals())

def quiz(request, quiz_id=None):
    if quiz_id is None:
        print("no id")
        quiz = Quiz(quid=id_generator(), expires_at=datetime.now()+timedelta(minutes=30))
        quiz.save()
        question_id_list = list(Question.objects.values_list('id', flat=True))
        question_id_list = random.sample(question_id_list,10)
        random.shuffle(question_id_list)
        questions = Question.objects.filter(id__in=question_id_list)
        for q in questions:
            quiz.questions.add(q)
        url = '/quiz/'+quiz.quid
        return HttpResponseRedirect(url)

    quiz = None
    if Quiz.objects.filter(quid=quiz_id, active=True).exists():
        quiz = Quiz.objects.get(quid=quiz_id, active=True)
        if (quiz.expires_at - datetime.now(timezone.utc)).total_seconds() >= 1800:
            quiz.active = False
            quiz.save()
            return HttpResponseRedirect('/quiz')
    else:
        return HttpResponseRedirect('/quiz')
    
    if request.POST:
        answer_id_list = []
        quiz.active=False
        quiz.save()
        for x in range(0,10):
            answer_id_list.append(request.POST.get("answers_"+str(x),None))
        print(answer_id_list)
        correct_answers = Answer.objects.filter(id__in=answer_id_list, is_correct=True).count()
        if correct_answers >= 7:
            validation_id = id_generator()
            request.session['name'] = request.POST.get('name')
            request.session['certificate_id'] = validation_id
            return HttpResponseRedirect('/certificate/'+validation_id)
        else:
            return HttpResponseRedirect('/failure')

    return render(request,'quiz.html',locals())

def failure(request):
    return render(request,'failure.html')

def certificate(request, validation_id=None):
    if validation_id is None:
        return HttpResponseRedirect('/quiz')
    certificate_id = request.session.get('certificate_id', None)
    if certificate_id != validation_id:
        return HttpResponseRedirect('/quiz')
    name = request.session.get('name', '')
    if request.POST:
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=landscape(letter))
        width, height = landscape(letter)
        c.setFont("Helvetica", 25)
        c.drawImage('template.png',0,0,width=width,height=height )
        c.drawCentredString(width/2,height/2,name)
        c.save()
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="Certificado.pdf"'
        pdf = buffer.getvalue()
        buffer.close()
        response.write(pdf)
        return response
    return render(request,'certificado.html', locals())


    
#-------------------------------------------------------------------
def id_generator(size=6, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

commons/templates/animales.html
<!DOCTYPE html>
<html>
<head>
 <meta charset="utf-8">
    <title>Animales</title>
 <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
body {


    font-family: "Montserrat", sans-serif;
}

.sidenav {

    height: 100%;
    width: 200px;
    margin-top: 50px;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #567E3A;
    overflow: auto;
    padding-top: 20px;
}

.sidenav a {
    padding: 6px 6px 12px 32px;
    text-decoration: none;
    font-size: 20px;
    color: #d5d5d5;
    display: block;
}

.sidenav a:hover {
    color: #2b384c;
}
.tab-content h1{
		text-align: left;
		font-size: 50px;

}	

.tab-content p{
		text-align: justify;
		margin-right: 45%;
}	
.tab-content {
  margin-top: 60px;
	text-align: justify;
    margin-left: 230px; 
}    
.picAnimal{
	  display: block;
    margin-left: 500px;
    margin-right: auto;
    margin-top: 1px;
    width: 50%;
}

.fondoTips {
  margin-top: 5%;
	 text-align: left; 
}

.mapaAnimal{
  display: block;
    margin-left: 500px;
    margin-right: auto;
    margin-top: 1px;
    width: 50%;
}
  
  .navbar {
      font-family: Montserrat, sans-serif;
      
      margin-bottom: 0;
      background-color: #567E3A;
      border: 0;
      font-size: 11px !important;
      letter-spacing: 4px;
      opacity: 0.9;
  }
  .navbar li a, .navbar .navbar-brand { 
      color: #d5d5d5 !important;
  }
  .navbar-nav li a:hover {
      color: #fff !important;
  }
  .navbar-nav li.active a {
      color: #fff !important;
      background-color: #29292c !important;
  }
  .navbar-default .navbar-toggle {
      border-color: transparent;
  }


@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
</head>
<body>


<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/" >ECOPEDIA</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
          <li><a href="/quiz/">TOMAR EXAMEN</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="sidenav">

  	<a class="tablinks" onclick="openAnimal(event,'Animales')" id="defaultOpen" >ANIMALES</a>
    {% for animal in animals %}
    <a class="tablinks" onclick="openAnimal(event,'{{animal.slug}}')"  >{{animal.name}}</a>
    {% endfor %}
</div>

<div class="tab-content">

 <div id="Animales" class="tabcontent">
  <h1>ANIMALES</h1>
  <p>Selecciona alguno de los animales para obtener información</p>

</div>
{% for animal in animals %}
<div id="{{animal.slug}}" class="tabcontent">
  <h1>{{animal.name}}</h1>
  <div class="picAnimal">
    <img  align="right" src="{{animal.image_link}}" width="400">
  </div>

  <p>{{animal.description}}</p> 

  <div class="fondoTips">
  	<h2>TIPS</h2>
    <div class="mapaAnimal">
    <img align="right"src= "{{animal.map_link}}" width="400">
  </div>
      {% for tip in animal.tip_set.all %}
      <ul >
        <li >{{tip.description}}</li>
      </ul>
      {% endfor %}
  </div>
</div>
{% endfor %}
</div>

<script>
function openAnimal(evt, animalName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(animalName).style.display = "block";
    evt.currentTarget.className += " active";
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>




     
</body>
</html> 

commons/templates/certificado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Reconocimiento</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <style type="text/css">

label.btn {
    padding: 18px 60px;
    white-space: normal;
    -webkit-transform: scale(1.0);
    -moz-transform: scale(1.0);
    -o-transform: scale(1.0);
    -webkit-transition-duration: .3s;
    -moz-transition-duration: .3s;
    -o-transition-duration: .3s
}


#buttonSubmit{
      text-align: center;


}
label.btn:hover {
    text-shadow: 0 3px 2px rgba(0,0,0,0.4);
    -webkit-transform: scale(1.1);
    -moz-transform: scale(1.1);
    -o-transform: scale(1.1)
}
label.btn-block {
    text-align: left;
    position: relative
}

label .btn-label {
    position: absolute;
    left: 0;
    top: 0;
    display: inline-block;
    padding: 0 10px;
    background: rgba(0,0,0,.15);
    height: 100%
}

label .glyphicon {
    top: 34%
}

/*
Animaciones que me robe
*/
.element-animation1 {
    animation: animationFrames ease .8s;
    animation-iteration-count: 1;
    transform-origin: 50% 50%;
    -webkit-animation: animationFrames ease .8s;
    -webkit-animation-iteration-count: 1;
    -webkit-transform-origin: 50% 50%;
    -ms-animation: animationFrames ease .8s;
    -ms-animation-iteration-count: 1;
    -ms-transform-origin: 50% 50%
}
.element-animation2 {
    animation: animationFrames ease 1s;
    animation-iteration-count: 1;
    transform-origin: 50% 50%;
    -webkit-animation: animationFrames ease 1s;
    -webkit-animation-iteration-count: 1;
    -webkit-transform-origin: 50% 50%;
    -ms-animation: animationFrames ease 1s;
    -ms-animation-iteration-count: 1;
    -ms-transform-origin: 50% 50%
}
.element-animation3 {
    animation: animationFrames ease 1.2s;
    animation-iteration-count: 1;
    transform-origin: 50% 50%;
    -webkit-animation: animationFrames ease 1.2s;
    -webkit-animation-iteration-count: 1;
    -webkit-transform-origin: 50% 50%;
    -ms-animation: animationFrames ease 1.2s;
    -ms-animation-iteration-count: 1;
    -ms-transform-origin: 50% 50%
}
.element-animation4 {
    animation: animationFrames ease 1.4s;
    animation-iteration-count: 1;
    transform-origin: 50% 50%;
    -webkit-animation: animationFrames ease 1.4s;
    -webkit-animation-iteration-count: 1;
    -webkit-transform-origin: 50% 50%;
    -ms-animation: animationFrames ease 1.4s;
    -ms-animation-iteration-count: 1;
    -ms-transform-origin: 50% 50%
}
.modal-header {
     font-family: "Montserrat", sans-serif;
    background-color: transparent;
    color: inherit
}

.modal-body {
     font-family: "Montserrat", sans-serif;
    min-height: 205px
}
.navbar {
      font-family: Montserrat, sans-serif;
      
      margin-bottom: 0;
      background-color: #567E3A;
      border: 0;
      font-size: 11px !important;
      letter-spacing: 4px;
      opacity: 0.9;
  }
  .navbar li a, .navbar .navbar-brand { 
      color: #d5d5d5 !important;
  }
  .navbar-nav li a:hover {
      color: #fff !important;
  }
  .navbar-nav li.active a {
      color: #fff !important;
      background-color: #29292c !important;
  }
  .navbar-default .navbar-toggle {
      border-color: transparent;
  }
.titulo{
     font-family: "Montserrat", sans-serif;
    text-align: center;
    }
.nombreFurro{
     font-family: "Montserrat", sans-serif;
    }
.active {
  background-color: blue !important;
}

/*
Modal header es el titulo de la carta
container-fluid bg-info es la carta en si, aqui adentro va todo
modalbody es donde van las respuestas
buttons es donde esta contenidos los inputs

*/

    </style>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/" >ECOPEDIA</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid bg-info">
<br>
<br>
<h1>Enhorabuena {{name}}, te haz ganado un reconocimiento</h1>
<form method=POST>
        {% csrf_token %}
    <input type="submit" class="btn btn-success" value="Obtener reconocimiento">
</form>
<br>
</div>
</body>
</html>

commons/templates/failure.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Oops</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <style type="text/css">

label.btn {
    padding: 18px 60px;
    white-space: normal;
    -webkit-transform: scale(1.0);
    -moz-transform: scale(1.0);
    -o-transform: scale(1.0);
    -webkit-transition-duration: .3s;
    -moz-transition-duration: .3s;
    -o-transition-duration: .3s
}


#buttonSubmit{
      text-align: center;


}
label.btn:hover {
    text-shadow: 0 3px 2px rgba(0,0,0,0.4);
    -webkit-transform: scale(1.1);
    -moz-transform: scale(1.1);
    -o-transform: scale(1.1)
}
label.btn-block {
    text-align: left;
    position: relative
}

label .btn-label {
    position: absolute;
    left: 0;
    top: 0;
    display: inline-block;
    padding: 0 10px;
    background: rgba(0,0,0,.15);
    height: 100%
}

label .glyphicon {
    top: 34%
}

/*
Animaciones que me robe
*/
.element-animation1 {
    animation: animationFrames ease .8s;
    animation-iteration-count: 1;
    transform-origin: 50% 50%;
    -webkit-animation: animationFrames ease .8s;
    -webkit-animation-iteration-count: 1;
    -webkit-transform-origin: 50% 50%;
    -ms-animation: animationFrames ease .8s;
    -ms-animation-iteration-count: 1;
    -ms-transform-origin: 50% 50%
}
.element-animation2 {
    animation: animationFrames ease 1s;
    animation-iteration-count: 1;
    transform-origin: 50% 50%;
    -webkit-animation: animationFrames ease 1s;
    -webkit-animation-iteration-count: 1;
    -webkit-transform-origin: 50% 50%;
    -ms-animation: animationFrames ease 1s;
    -ms-animation-iteration-count: 1;
    -ms-transform-origin: 50% 50%
}
.element-animation3 {
    animation: animationFrames ease 1.2s;
    animation-iteration-count: 1;
    transform-origin: 50% 50%;
    -webkit-animation: animationFrames ease 1.2s;
    -webkit-animation-iteration-count: 1;
    -webkit-transform-origin: 50% 50%;
    -ms-animation: animationFrames ease 1.2s;
    -ms-animation-iteration-count: 1;
    -ms-transform-origin: 50% 50%
}
.element-animation4 {
    animation: animationFrames ease 1.4s;
    animation-iteration-count: 1;
    transform-origin: 50% 50%;
    -webkit-animation: animationFrames ease 1.4s;
    -webkit-animation-iteration-count: 1;
    -webkit-transform-origin: 50% 50%;
    -ms-animation: animationFrames ease 1.4s;
    -ms-animation-iteration-count: 1;
    -ms-transform-origin: 50% 50%
}
.modal-header {
     font-family: "Montserrat", sans-serif;
    background-color: transparent;
    color: inherit
}

.modal-body {
     font-family: "Montserrat", sans-serif;
    min-height: 205px
}
.navbar {
      font-family: Montserrat, sans-serif;
      
      margin-bottom: 0;
      background-color: #567E3A;
      border: 0;
      font-size: 11px !important;
      letter-spacing: 4px;
      opacity: 0.9;
  }
  .navbar li a, .navbar .navbar-brand { 
      color: #d5d5d5 !important;
  }
  .navbar-nav li a:hover {
      color: #fff !important;
  }
  .navbar-nav li.active a {
      color: #fff !important;
      background-color: #29292c !important;
  }
  .navbar-default .navbar-toggle {
      border-color: transparent;
  }
.titulo{
     font-family: "Montserrat", sans-serif;
    text-align: center;
    }
.nombreFurro{
     font-family: "Montserrat", sans-serif;
    }
.active {
  background-color: blue !important;
}

/*
Modal header es el titulo de la carta
container-fluid bg-info es la carta en si, aqui adentro va todo
modalbody es donde van las respuestas
buttons es donde esta contenidos los inputs

*/

    </style>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/" >ECOPEDIA</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid bg-info">
<br>
<br>
<h1>Vaya, parece que no lo haz logrado</h1>
<a href="/quiz"><h2>Intentar de nuevo</h2></a>
<br>
</div>
</body>
</html>

commons/templates/quiz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Quiz</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <style type="text/css">

label.btn {
    padding: 18px 60px;
    white-space: normal;
    -webkit-transform: scale(1.0);
    -moz-transform: scale(1.0);
    -o-transform: scale(1.0);
    -webkit-transition-duration: .3s;
    -moz-transition-duration: .3s;
    -o-transition-duration: .3s
}


#buttonSubmit{
      text-align: center;


}
label.btn:hover {
    text-shadow: 0 3px 2px rgba(0,0,0,0.4);
    -webkit-transform: scale(1.1);
    -moz-transform: scale(1.1);
    -o-transform: scale(1.1)
}
label.btn-block {
    text-align: left;
    position: relative
}

label .btn-label {
    position: absolute;
    left: 0;
    top: 0;
    display: inline-block;
    padding: 0 10px;
    background: rgba(0,0,0,.15);
    height: 100%
}

label .glyphicon {
    top: 34%
}

/*
Animaciones que me robe
*/
.element-animation1 {
    animation: animationFrames ease .8s;
    animation-iteration-count: 1;
    transform-origin: 50% 50%;
    -webkit-animation: animationFrames ease .8s;
    -webkit-animation-iteration-count: 1;
    -webkit-transform-origin: 50% 50%;
    -ms-animation: animationFrames ease .8s;
    -ms-animation-iteration-count: 1;
    -ms-transform-origin: 50% 50%
}
.element-animation2 {
    animation: animationFrames ease 1s;
    animation-iteration-count: 1;
    transform-origin: 50% 50%;
    -webkit-animation: animationFrames ease 1s;
    -webkit-animation-iteration-count: 1;
    -webkit-transform-origin: 50% 50%;
    -ms-animation: animationFrames ease 1s;
    -ms-animation-iteration-count: 1;
    -ms-transform-origin: 50% 50%
}
.element-animation3 {
    animation: animationFrames ease 1.2s;
    animation-iteration-count: 1;
    transform-origin: 50% 50%;
    -webkit-animation: animationFrames ease 1.2s;
    -webkit-animation-iteration-count: 1;
    -webkit-transform-origin: 50% 50%;
    -ms-animation: animationFrames ease 1.2s;
    -ms-animation-iteration-count: 1;
    -ms-transform-origin: 50% 50%
}
.element-animation4 {
    animation: animationFrames ease 1.4s;
    animation-iteration-count: 1;
    transform-origin: 50% 50%;
    -webkit-animation: animationFrames ease 1.4s;
    -webkit-animation-iteration-count: 1;
    -webkit-transform-origin: 50% 50%;
    -ms-animation: animationFrames ease 1.4s;
    -ms-animation-iteration-count: 1;
    -ms-transform-origin: 50% 50%
}
@keyframes animationFrames {
    0% {
        opacity: 0;
        transform: translate(-1500px,0px)
    }

    60% {
        opacity: 1;
        transform: translate(30px,0px)
    }

    80% {
        transform: translate(-10px,0px)
    }

    100% {
        opacity: 1;
        transform: translate(0px,0px)
    }
}

@-webkit-keyframes animationFrames {
    0% {
        opacity: 0;
        -webkit-transform: translate(-1500px,0px)
    }
    60% {
        opacity: 1;
        -webkit-transform: translate(30px,0px)
    }

    80% {
        -webkit-transform: translate(-10px,0px)
    }

    100% {
        opacity: 1;
        -webkit-transform: translate(0px,0px)
    }
}

@-ms-keyframes animationFrames {
    0% {
        opacity: 0;
        -ms-transform: translate(-1500px,0px)
    }

    60% {
        opacity: 1;
        -ms-transform: translate(30px,0px)
    }
    80% {
        -ms-transform: translate(-10px,0px)
    }

    100% {
        opacity: 1;
        -ms-transform: translate(0px,0px)
    }
}

.modal-header {
     font-family: "Montserrat", sans-serif;
    background-color: transparent;
    color: inherit
}

.modal-body {
     font-family: "Montserrat", sans-serif;
    min-height: 205px
}
.navbar {
      font-family: Montserrat, sans-serif;
      
      margin-bottom: 0;
      background-color: #567E3A;
      border: 0;
      font-size: 11px !important;
      letter-spacing: 4px;
      opacity: 0.9;
  }
  .navbar li a, .navbar .navbar-brand { 
      color: #d5d5d5 !important;
  }
  .navbar-nav li a:hover {
      color: #fff !important;
  }
  .navbar-nav li.active a {
      color: #fff !important;
      background-color: #29292c !important;
  }
  .navbar-default .navbar-toggle {
      border-color: transparent;
  }
.titulo{
     font-family: "Montserrat", sans-serif;
    text-align: center;
    }
.nombreFurro{
     font-family: "Montserrat", sans-serif;
     width: 50%;
     text-align:center;
     margin:auto;
    }
.active {
  background-color: blue !important;
}

/*
Modal header es el titulo de la carta
container-fluid bg-info es la carta en si, aqui adentro va todo
modalbody es donde van las respuestas
buttons es donde esta contenidos los inputs

*/

    </style>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/" >ECOPEDIA</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid bg-info">
<br>
<br>
<form method="POST">
{% csrf_token %}
<div class="titulo">
    <H1 text-align="center">EXAMEN ECOPEDIA</H1>
</div>
<div class="nombreFurro">
    <label for="inputNombreDelFurro">Nombre</label>
    <input type="name" class="form-control" id="inputName" name="name" autocomplete="off" >
</div>
{% for q in quiz.questions.all %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3>{{q.description}}</h3>
            </div>
            <div class="modal-body">
                <div class="quiz" id="quiz" data-toggle="buttons">
                    {% for a in q.answer_set.all %}
                    <label class="element-animation1 btn btn-lg btn-success btn-block"><span class="btn-label"><i class="glyphicon glyphicon-chevron-right"></i></span> <input type="radio" name="answers_{{forloop.parentloop.counter0}}" value={{a.id}}>{{a.description}}</label>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endfor %}
</div>
<div class="container-fluid bg-info">
<div id="buttonSubmit">
  <button type="submit" class="btn btn-success">FINALIZAR EXAMEN</button>  
</div>
</form>
<br>
</div>
</body>
</html>